### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by bizehao** [CoderLengary/WanAndroid#2]
刚刚clone下来，用as打包到我的手机上  [点开某一个文章，就会应用强制关闭
这是错误信息  我看不太懂   还有  大佬  你们的项目都不写注释的吗 - -！
E/linker: normalize_path - invalid input: "null", the input path should be absolute

A/zygote64: java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
            java_vm_ext.cc:504]     in call to GetStringUTFChars
            java_vm_ext.cc:504]     from int android.webkit.WebViewFactory.nativeLoadWithRelroFile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader)
            java_vm_ext.cc:504] "main" prio=5 tid=1 Runnable
            java_vm_ext.cc:504]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x73c2ff50 self=0x78736c0a00
            java_vm_ext.cc:504]   | sysTid=31951 nice=-10 cgrp=default sched=0/0 handle=0x7878c629c8
            java_vm_ext.cc:504]   | state=R schedstat=( 3567589382 164844433 1059 ) utm=320 stm=36 core=7 HZ=100
            java_vm_ext.cc:504]   | stack=0x7fee392000-0x7fee394000 stackSize=8MB
            java_vm_ext.cc:504]   | held mutexes= "mutator lock"(shared held)
            java_vm_ext.cc:504]   native: #00 pc 00000000003aeac4  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
            java_vm_ext.cc:504]   native: #01 pc 000000000047ddec  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
            java_vm_ext.cc:504]   native: #02 pc 00000000002e61c0  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1040)
            java_vm_ext.cc:504]   native: #03 pc 00000000002e6664  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)

**Comment by CoderLengary** [comment]
你好，十分抱歉现在才回复，之前写这个项目的时候中间出了点事，所以断了好长时间，到弄完事情后，秋招就要开始了，时间不够了，所以注释啥的就写得很少，后面会写上注释的。。。而针对于你的第一个问题，我刚刚用了一个新电脑去clone，并加载到手机上，而且用了一个新账号，点击文章的时候并没有出现这个错误。我的同学新安装了这个应用，也没有发现问题。你可以尝试下在AVD上运行，看效果怎么样。
